(()=>{
const API2=window.API||'https://stockpulse-india-api-v3.onrender.com/api';
const sec=()=>document.getElementById('broker-calls');
async function loadBrokerCalls(){const el=sec();if(!el)return;el.style.display='block';el.classList.remove('hidden');el.innerHTML='<div class="panel"><div class="hero"><div><h2>Broker & Analyst Calls</h2><p class="muted">Live public brokerage/research calls are shown separately from StockPulse scoring.</p></div><button class="btn" id="broker-refresh">↻ Refresh calls</button></div><div id="broker-calls-body">Loading public research calls…</div></div>';const body=document.getElementById('broker-calls-body');const refresh=document.getElementById('broker-refresh');if(refresh)refresh.onclick=loadBrokerCalls;try{const r=await fetch(API2+'/broker-recommendations?limit=200',{cache:'no-store'});if(!r.ok)throw Error('HTTP '+r.status);const d=await r.json();const rows=Array.isArray(d.items)?d.items:[];if(rows.length){body.innerHTML=`<div class="tablewrap"><table class="table"><thead><tr><th>Stock</th><th>Broker / Analyst</th><th>Rating</th><th>Target</th><th>Current</th><th>Upside</th><th>Date</th><th>Reason</th><th>Source</th></tr></thead><tbody>${rows.map(x=>`<tr><td><b>${x.company||x.symbol||'—'}</b><br><small>${x.company&&x.symbol!==x.company?x.symbol:''}</small></td><td>${x.broker||x.source||'—'}${x.analyst?' / '+x.analyst:''}</td><td>${x.rating||'—'}</td><td>${x.target_price??'—'}</td><td>${x.current_price??'—'}</td><td>${x.upside_pct!=null?Number(x.upside_pct).toFixed(1)+'%':'—'}</td><td>${x.date||'—'}</td><td>${x.rationale||'—'}</td><td>${x.source_url?`<a href="${x.source_url}" target="_blank" rel="noopener">View report</a>`:'—'}</td></tr>`).join('')}</tbody></table></div><p class="muted">Source feed: ${d.data_source||'Public research listings'} • ${rows.length} calls loaded</p>`}else{body.innerHTML='<div class="empty">No public broker/analyst calls were returned by the connected sources right now. The section will remain visible; use Refresh calls to retry the public feeds.</div>'}}catch(e){body.innerHTML='<div class="empty">Broker feed temporarily unavailable. The section is kept visible. Use Refresh calls to retry.</div>'}}
function init(){const el=sec();if(el)loadBrokerCalls();else{const main=document.querySelector('main');if(main){const s=document.createElement('section');s.id='broker-calls';s.className='section';main.appendChild(s);loadBrokerCalls()}}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
const oldLoad=window.load;
if(typeof oldLoad==='function'){
 window.load=async function(){try{const r=await fetch(API2+'/screener/top?limit=5000&min_quality=0',{cache:'no-store'});if(!r.ok)throw Error(r.status);const d=await r.json();window.all=d.items||[];const st=document.getElementById('status');if(st)st.textContent='Updated '+new Date(d.generated_at||Date.now()).toLocaleTimeString()+' • '+(d.universe_size||window.all.length)+' stocks';if(typeof window.render==='function')window.render();if(!document.getElementById('market')?.classList.contains('hidden')&&typeof window.renderMarket==='function')window.renderMarket();const b=sec();if(b){b.style.display='block';b.classList.remove('hidden')}}catch(e){oldLoad();const b=sec();if(b){b.style.display='block';b.classList.remove('hidden')}}};
 setTimeout(()=>window.load(),800);
}
window.renderMarket=async function(){let idx=[];try{const r=await fetch(API2+'/market',{cache:'no-store'});if(r.ok)idx=(await r.json()).indices||[]}catch(e){}const by={};idx.forEach(x=>by[x.symbol]=x);const n=by['NIFTY 50'],s=by['SENSEX'];const fmt=x=>x&&x.price!=null?'₹'+Number(x.price).toLocaleString('en-IN',{maximumFractionDigits:2}):'—';const pct=x=>x&&x.change_pct!=null?((Number(x.change_pct)>=0?'+':'')+Number(x.change_pct).toFixed(2)+'%'):'Data unavailable';const mc=document.getElementById('mc');if(mc)mc.innerHTML=[['NIFTY 50',n],['SENSEX',s],['NIFTY BANK',by['NIFTY BANK']]].map(([name,x])=>`<div class="stat"><h3>${name}</h3><b class="big">${fmt(x)}</b><span class="${x&&Number(x.change_pct)>=0?'up':'down'}">${pct(x)}</span></div>`).join('');if(typeof window.all!=='undefined'){const a=window.all.filter(x=>Number(x.change_pct)>0).length,d=window.all.filter(x=>Number(x.change_pct)<0).length,f=window.all.length-a-d;document.getElementById('madv').textContent=a;document.getElementById('mdec').textContent=d;document.getElementById('mflat').textContent=f;document.getElementById('mratio').textContent=d?(a/d).toFixed(2):'—';const sectors={};window.all.forEach(x=>{const k=x.sector||'Other';(sectors[k]??=[]).push(x)});document.getElementById('sectors').innerHTML=Object.entries(sectors).sort((a,b)=>b[1].reduce((z,x)=>z+Number(x.change_pct||0),0)-a[1].reduce((z,x)=>z+Number(x.change_pct||0),0)).slice(0,12).map(([k,v])=>`<div class="stat"><b>${k}</b><span>${v.length} stocks</span><small>Avg ${(v.reduce((z,x)=>z+Number(x.change_pct||0),0)/v.length).toFixed(2)}%</small></div>`).join('')}};
})();