(()=>{
const API2=window.API||'https://stockpulse-india-api-v3.onrender.com/api';
async function loadBrokerCalls(){const sec=document.getElementById('broker-calls');if(!sec)return;sec.innerHTML='<div class="panel"><h2>Broker & Analyst Calls</h2><p class="muted">Live public brokerage/research calls are shown separately from StockPulse scoring. Ratings, targets and dates come from the cited public research listings.</p><div id="broker-calls-body">Loading…</div></div>';try{const r=await fetch(API2+'/broker-recommendations',{cache:'no-store'});const d=await r.json();const rows=d.items||[];document.getElementById('broker-calls-body').innerHTML=rows.length?`<div class="tablewrap"><table class="table"><thead><tr><th>Stock</th><th>Broker / Analyst</th><th>Rating</th><th>Target</th><th>Current</th><th>Upside</th><th>Date</th><th>Reason</th><th>Source</th></tr></thead><tbody>${rows.map(x=>`<tr><td><b>${x.company||x.symbol||'—'}</b><br><small>${x.company&&x.symbol!==x.company?x.symbol:''}</small></td><td>${x.broker||x.source||'—'}${x.analyst?' / '+x.analyst:''}</td><td>${x.rating||'—'}</td><td>${x.target_price??'—'}</td><td>${x.current_price??'—'}</td><td>${x.upside_pct!=null?Number(x.upside_pct).toFixed(1)+'%':'—'}</td><td>${x.date||'—'}</td><td>${x.rationale||'—'}</td><td>${x.source_url?`<a href="${x.source_url}" target="_blank" rel="noopener">View report</a>`:'—'}</td></tr>`).join('')}</tbody></table></div><p class="muted">Source feed: ${d.data_source||'Public research listings'} • ${d.items.length} calls loaded</p>`:'<div class="empty">No public broker/analyst calls were returned by the connected sources right now.</div>'}catch(e){document.getElementById('broker-calls-body').innerHTML='<div class="empty">Broker feed unavailable right now.</div>'}}
function init(){if(document.getElementById('broker-calls'))loadBrokerCalls();else{const main=document.querySelector('main');if(main){const s=document.createElement('section');s.id='broker-calls';s.className='section';main.appendChild(s);loadBrokerCalls()}}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
const oldLoad=window.load;
if(typeof oldLoad==='function'){
 window.load=async function(){try{const r=await fetch(API2+'/screener/top?limit=5000&min_quality=0',{cache:'no-store'});if(!r.ok)throw Error(r.status);const d=await r.json();window.all=d.items||[];const st=document.getElementById('status');if(st)st.textContent='Updated '+new Date(d.generated_at||Date.now()).toLocaleTimeString()+' • '+(d.universe_size||window.all.length)+' stocks';if(typeof window.render==='function')window.render();if(!document.getElementById('market')?.classList.contains('hidden')&&typeof window.renderMarket==='function')window.renderMarket()}catch(e){oldLoad()}};
 setTimeout(()=>window.load(),800);
}
window.renderMarket=async function(){let idx=[];try{const r=await fetch(API2+'/market',{cache:'no-store'});if(r.ok)idx=(await r.json()).indices||[]}catch(e){}const by={};idx.forEach(x=>by[x.symbol]=x);const n=by['NIFTY 50'],s=by['SENSEX'];const fmt=x=>x&&x.price!=null?'₹'+Number(x.price).toLocaleString('en-IN',{maximumFractionDigits:2}):'—';const pct=x=>x&&x.change_pct!=null?((Number(x.change_pct)>=0?'+':'')+Number(x.change_pct).toFixed(2)+'%'):'Data unavailable';const mc=document.getElementById('mc');if(mc)mc.innerHTML=[['NIFTY 50',n],['SENSEX',s],['NIFTY BANK',by['NIFTY BANK']]].map(([name,x])=>`<div class="stat"><h3>${name}</h3><b class="big">${fmt(x)}</b><span class="${x&&Number(x.change_pct)>=0?'up':'down'}">${pct(x)}</span></div>`).join('');if(typeof window.all!=='undefined'){const a=window.all.filter(x=>Number(x.change_pct)>0).length,d=window.all.filter(x=>Number(x.change_pct)<0).length,f=window.all.length-a-d;document.getElementById('madv').textContent=a;document.getElementById('mdec').textContent=d;document.getElementById('mflat').textContent=f;document.getElementById('mratio').textContent=d?(a/d).toFixed(2):'—';const sectors={};window.all.forEach(x=>{const k=x.sector||'Other';(sectors[k]??=[]).push(x)});document.getElementById('sectors').innerHTML=Object.entries(sectors).sort((a,b)=>b[1].reduce((z,x)=>z+Number(x.change_pct||0),0)-a[1].reduce((z,x)=>z+Number(x.change_pct||0),0)).slice(0,12).map(([k,v])=>`<div class="stat"><b>${k}</b><span>${v.length} stocks</span><small>Avg ${(v.reduce((z,x)=>z+Number(x.change_pct||0),0)/v.length).toFixed(2)}%</small></div>`).join('')}};
})();