(()=>{
const API2=window.API||'https://stockpulse-india-api-v3.onrender.com/api';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=x=>'₹'+(Number(x||0)).toLocaleString('en-IN',{maximumFractionDigits:2});
async function j(path){try{const r=await fetch(API2+path,{cache:'no-store'});return await r.json()}catch(e){return {items:[],error:String(e)}}}
function addTab(id,label){if(document.querySelector(`[data-tab="${id}"]`))return;const nav=document.querySelector('#tabs');const b=document.createElement('button');b.dataset.tab=id;b.textContent=label;nav.appendChild(b)}
function addSection(id,title,sub=''){if(document.getElementById(id))return;const main=document.querySelector('main');const footer=main.querySelector('footer');const s=document.createElement('section');s.id=id;s.className='hidden';s.innerHTML=`<div class="hero"><div><h1>${title}</h1><p class="muted">${sub}</p></div><button class="btn" onclick="suiteLoad('${id}')">↻ Refresh</button></div><div id="${id}-body"></div>`;main.insertBefore(s,footer)}
function bindTabs(){document.querySelectorAll('#tabs button').forEach(b=>b.addEventListener('click',()=>{if(['dividends','corporate','analytics','orders'].includes(b.dataset.tab))suiteLoad(b.dataset.tab)}))}
window.suiteLoad=async function(id){const el=document.getElementById(id+'-body');if(!el)return;el.innerHTML='<div class="panel">Loading…</div>';if(id==='dividends'){const d=await j('/dividends');el.innerHTML=`<div class="panel"><div class="filters"><label>Minimum dividend yield %<input id="dymin" type="number" value="0" step="0.1"></label><label>Search symbol<input id="dys" placeholder="RELIANCE"></label></div><div class="tablewrap"><table class="table"><thead><tr><th>Symbol</th><th>Purpose</th><th>Ex-date</th><th>Record date</th><th>Dividend</th></tr></thead><tbody>${(d.items||[]).map(x=>`<tr onclick="detail('${esc(x.symbol)}')"><td><b>${esc(x.symbol)}</b></td><td>${esc(x.purpose)}</td><td>${esc(x.ex_date||'—')}</td><td>${esc(x.record_date||'—')}</td><td>${esc(x.dividend||'—')}</td></tr>`).join('')||'<tr><td colspan="5" class="empty">No dividend actions returned by the live exchange feed.</td></tr>'}</tbody></table></div></div>`}
else if(id==='corporate'){const [a,b]=await Promise.all([j('/corporate-actions'),j('/board-meetings')]);el.innerHTML=`<div class="grid"><div class="panel"><h3>Corporate actions</h3><div class="tablewrap"><table class="table"><thead><tr><th>Symbol</th><th>Purpose</th><th>Ex-date</th></tr></thead><tbody>${(a.items||[]).map(x=>`<tr onclick="detail('${esc(x.symbol)}')"><td>${esc(x.symbol)}</td><td>${esc(x.purpose)}</td><td>${esc(x.ex_date||'—')}</td></tr>`).join('')||'<tr><td colspan="3" class="empty">No live actions returned.</td></tr>'}</tbody></table></div></div><div class="panel"><h3>Board meetings</h3><div class="tablewrap"><table class="table"><thead><tr><th>Symbol</th><th>Purpose</th><th>Date</th></tr></thead><tbody>${(b.items||[]).map(x=>`<tr onclick="detail('${esc(x.symbol)}')"><td>${esc(x.symbol)}</td><td>${esc(x.purpose||'—')}</td><td>${esc(x.meeting_date||'—')}</td></tr>`).join('')||'<tr><td colspan="3" class="empty">No live meetings returned.</td></tr>'}</tbody></table></div></div></div>`}
else if(id==='analytics'){el.innerHTML=`<div class="panel"><h3>Stock intelligence</h3><p class="muted">Select any stock from Screener/Watchlist to open the complete analysis. The engine combines fundamentals 35%, valuation 20%, technical/momentum 20%, catalysts 15%, and risk 10%.</p><div class="trade"><label>Symbol<input id="suiteSymbol" placeholder="TCS"></label><button class="btn" onclick="suiteAnalyze()">Analyze stock</button></div></div><div id="suite-analysis"></div>`}
else if(id==='orders'){el.innerHTML=`<div class="panel"><h3>Order planner</h3><p class="muted">Personal-use planning only; no broker execution or real-money order is sent.</p><div class="trade"><label>Symbol<input id="os"></label><label>Side<select id="side"><option>BUY</option><option>SELL</option></select></label><label>Quantity<input id="oq" type="number"></label><label>Price<input id="op" type="number"></label><button class="btn" onclick="planOrder()">Add to plan</button></div></div><div class="panel section"><div class="tablewrap"><table class="table"><thead><tr><th>Time</th><th>Symbol</th><th>Side</th><th>Qty</th><th>Price</th><th>Value</th><th></th></tr></thead><tbody id="orders-table"></tbody></table></div></div>`;renderOrders()}};
window.suiteAnalyze=async function(){const s=(document.getElementById('suiteSymbol')?.value||'').trim().toUpperCase();if(!s)return;const [a,b,c]=await Promise.all([j('/analytics/'+encodeURIComponent(s)),j('/corporate-actions?symbol='+encodeURIComponent(s)),j('/shareholding/'+encodeURIComponent(s))]);document.getElementById('suite-analysis').innerHTML=`<div class="grid"><div class="panel"><h3>${esc(s)} — Quant score</h3><div class="big">${esc(a.technical?.momentum_score??'—')}</div><div>Trend: ${esc(a.technical?.trend||'—')}</div><div>1D ${esc(a.returns?.['1D']||0)}% • 1M ${esc(a.returns?.['1M']||0)}% • 1Y ${esc(a.returns?.['1Y']||0)}%</div></div><div class="panel"><h3>Corporate actions</h3>${(b.items||[]).slice(0,8).map(x=>`<p><b>${esc(x.purpose)}</b><br><small>${esc(x.ex_date||'')}</small></p>`).join('')||'<p class="muted">No actions returned.</p>'}</div><div class="panel"><h3>Shareholding</h3><pre style="white-space:pre-wrap;max-height:300px;overflow:auto">${esc(JSON.stringify(c.items||[],null,2))}</pre></div></div>`}
function renderOrders(){const rows=JSON.parse(localStorage.getItem('sporders')||'[]');const t=document.getElementById('orders-table');if(!t)return;t.innerHTML=rows.map((x,i)=>`<tr><td>${esc(x.time)}</td><td>${esc(x.symbol)}</td><td>${esc(x.side)}</td><td>${x.qty}</td><td>${money(x.price)}</td><td>${money(x.qty*x.price)}</td><td><button class="btn" onclick="removeOrder(${i})">Remove</button></td></tr>`).join('')||'<tr><td colspan="7" class="empty">No planned orders.</td></tr>'}
window.planOrder=()=>{const symbol=(document.getElementById('os')?.value||'').trim().toUpperCase(),side=document.getElementById('side')?.value,qty=Number(document.getElementById('oq')?.value),price=Number(document.getElementById('op')?.value);if(!symbol||qty<=0||price<=0)return;const r=JSON.parse(localStorage.getItem('sporders')||'[]');r.push({time:new Date().toLocaleString('en-IN'),symbol,side,qty,price});localStorage.setItem('sporders',JSON.stringify(r));renderOrders()};window.removeOrder=i=>{const r=JSON.parse(localStorage.getItem('sporders')||'[]');r.splice(i,1);localStorage.setItem('sporders',JSON.stringify(r));renderOrders()};
function init(){['dividends','corporate','analytics','orders'].forEach((id,i)=>addTab(id,['Dividends','Corporate Actions','Analytics','Order Planner'][i]));['dividends','corporate','analytics','orders'].forEach((id,i)=>addSection(id,['Dividends','Corporate Actions','Stock Analytics','Order Planner'][i],['Dividend history, yield screening and upcoming dates.','Dividend, bonus, split, rights, buyback and board-meeting intelligence.','Deep stock analysis and recommendation framework.','Buy/sell planning, quantities, prices and portfolio workflow.'][i]));bindTabs();try{const old=window.detail;if(old)window.detail=async s=>{old(s);setTimeout(async()=>{const box=document.getElementById('db');if(!box)return;const a=await j('/analytics/'+encodeURIComponent(s));const c=await j('/corporate-actions?symbol='+encodeURIComponent(s));const b=await j('/board-meetings?symbol='+encodeURIComponent(s));let z=document.getElementById('suite-detail-extra');if(!z){z=document.createElement('div');z.id='suite-detail-extra';z.className='section';box.appendChild(z)}z.innerHTML=`<div class="panel"><h3>StockPulse Intelligence</h3><div class="detailgrid"><div class="stat"><b>${esc(a.technical?.momentum_score??'—')}</b><span>Momentum score</span></div><div class="stat"><b>${esc(a.technical?.trend||'—')}</b><span>Trend</span></div><div class="stat"><b>${esc((a.returns?.['1Y']??0)+'%')}</b><span>1Y return</span></div><div class="stat"><b>${esc((a.volume?.signal)||'—')}</b><span>Volume signal</span></div></div><h4>Corporate actions</h4>${(c.items||[]).slice(0,6).map(x=>`<p>${esc(x.purpose)} — ${esc(x.ex_date||'')}</p>`).join('')||'<p class="muted">No actions returned.</p>'}<h4>Board meetings</h4>${(b.items||[]).slice(0,6).map(x=>`<p>${esc(x.purpose||'—')} — ${esc(x.meeting_date||'')}</p>`).join('')||'<p class="muted">No meetings returned.</p>'}</div>`},250)}}catch(e){}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
